### ISSUE TITLE
Add a test for UNSUBSCRIBE

### ISSUE THREAD

**Issue by jpwsutton** [eclipse/paho.mqtt.testing#1]
migrated from Bugzilla [#476802](https://bugs.eclipse.org/bugs/show_bug.cgi?id=476802)
status UNCONFIRMED severity _normal_ in component _MQTT Interop Tests_ for _1.2_
Reported in version _unspecified_ on platform _PC_
Assigned to: Ian Craggs

Original attachment names and IDs:
- _[0001-Unsubscribe-test.patch](https://bugs.eclipse.org/bugs//attachment.cgi?id=256422)_ (ID 256422)

On 2015-09-07 09:50:39 -0400, Pierre-Henri Trivier wrote:

> Created attachment 256422
> unsubscribe test
> 
> The "UNSUBSCRIBE" message type does not seem to be tested. 
> 
> This patch adds a simple unsubscribe test.

**Comment by icraggs** [comment]
I've added the test for unsubscribe.  Thanks.
