### ISSUE TITLE
MQTTV5: Session expiry

### ISSUE THREAD

**Issue by icraggs** [eclipse/paho.mqtt.testing#15]
Split the Clean Session flag into a Clean Start flag which indicates that the session should start without using an existing session, and a Session Expiry interval which says how long to retain the session after a disconnect. The session expiry interval can be modified at disconnect. Setting of Clean Start to 1 and Session Expiry Interval to 0 is equivalent in MQTT v3.1.1 of setting Clean Session to 1.

**Comment by icraggs** [comment]
The session expiry property is valid on connect and disconnect.

If the session expiry on re-connect is omitted, does that override the existing setting in the saved state, or re-use the original?  I think it overrides to 'never' according to the wording, but the other interpretation seems cleaner.

There is no way that I can see to set expiry to 'never' on disconnect, as omitting the property means adopting that set at connect.

**Comment by icraggs** [comment]
Done, except for throwing protocol error if the session expiry on disconnect is >0 when the one on connect was 0.

**Comment by icraggs** [comment]
Now done.

**Comment by dberardo-com** [comment]
is there any piece of documentation that states how to set the session expiry interval on new connections ? i cant find any reference on the python doc page.

**Comment by fpagliughi** [comment]
When connecting, you need to set the "clean start" to false (to say that you want a persistent session on the server), and then you add a _property_ to the connect message for the session expiry interval with the time that you want.

You're right, I don't see an example in the Python client showing how to do this. We should put something up there, as this is fairly common/important for v5.

But here's an example from the Paho C++ library showing how to do it. I assume it should be easy enough to convert it to Python. It tells the server to keep the session for 1 week (604800 sec).

[Paho C++ async_consume_v5.cpp session expiry](https://github.com/eclipse/paho.mqtt.cpp/blob/3631bce7e0bd74cc11a46410669ccd2e23b6caed/examples/async_consume_v5.cpp#L52-L61)
