### ISSUE TITLE
TLS layer enablement

### ISSUE THREAD

**Issue by hmchaitra** [eclipse/paho.mqtt.testing#43]
Hi,
in paho 3.1.1 how to enable a tls layer at broker side?..is their a provision for tls layer??

**Comment by icraggs** [comment]
This broker does not currently have TLS support, but it is actually quite easy in Python, so I may well add it.  Conversely, if you want to submit a PR to add it, then I'll be happy to look at it :-)

**Comment by hmchaitra** [comment]
i went through ssl module of python, i will give a try,and if i fail i will let you know.

Thank you

**Comment by icraggs** [comment]
FYI, I've now added TLS support to the V311 broker.  I will add the ability to configure through a config file at some point.

**Comment by hmchaitra** [comment]
Thank you soo much sir.

**Comment by susheelat** [comment]
README file for tls security is not updated. Can you please help me out to run MQTT3.1 with tls support?.

**Comment by icraggs** [comment]
I've updated the README, and there is a config file for client testing: client_testing.conf which shows how to do this.

**Comment by icraggs** [comment]
Done.
