### ISSUE TITLE
[MQTT-3.2.2-2 Session Present] interoperability/client_test.py should check session present flag

### ISSUE THREAD

**Issue by jpwsutton** [eclipse/paho.mqtt.testing#5]
migrated from Bugzilla [#443451](https://bugs.eclipse.org/bugs/show_bug.cgi?id=443451)
status UNCONFIRMED severity _trivial_ in component _MQTT Interop Tests_ for _1.2_
Reported in version _unspecified_ on platform _All_
Assigned to: Ian Craggs

On 2014-09-06 12:57:12 -0400, Shuhei Tanuma wrote:

> MQTT Interop tests doesn't check session present flag if there is a session.
> We supposed MQTT-3.2.2-2 spec might overlook.
> 
> it would be helpful if `interoperability/client_test.py` checks the flag.

**Comment by icraggs** [comment]
Fixed in mqttv5 branch.
